### ISSUE TITLE
Question on minTypicalAge / maxTypicalAge

### ISSUE THREAD

**Issue by barthanssens** [healthDCAT-AP/draft#4]
Not being an eHealth expert, I'm not sure what "typical" means.

Is it something like 95% of the people in the dataset are older than the minTypicalAge, younger than the maxTypicalAge ?
Or is this flexible, i.e. data owners decides what it means in practice

**Comment by healthDCAT-AP** [comment]
If a data owner has in his dataset a senior who is 105 years of old, the data holder can't provide maxTypicalAge = 105 because that a sensitive information related to an individual. Instead the data holder will provide a typical max age of 100 for example.

**Comment by BrendaHijmans** [comment]
I would advise to make this explanation clear in the documentation.
