### ISSUE TITLE
Inconsistency in casing of numberof properties

### ISSUE THREAD

**Issue by barthanssens** [healthDCAT-AP/draft#6]
Throughout the document, various slightly different ways of writing the numberOfRecords and numberOfUniqueIndividuals are being used

E.g in the example section `healthdcatap:numberOfrecords` (lowercase `r`, uppercase `O` ) and `healthdcatap:numberOfUniqueIndividuals`  (uppercase `U` and `O`)
But `healthdcatap: numberofUniqueIndividuals` (lowercase `o`) and `healthdcatap:numberofRecords`  (lowercase `o`) in the Dataset section

**Comment by healthDCAT-AP** [comment]
Dear Bart, Thank for pointing out these clerical errors. Pascal

**Comment by healthDCAT-AP** [comment]
Dear Bart, Thank for pointing out these clerical errors. Pascal
